<?php

/**
 * @file
 * Contains az_blob_fs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_blob_fs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the az_blob_fs module.
    case 'help.page.az_blob_fs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module create a stream wrapper scheme in order to store files on the Azure Storage cloud service') . '</p>';
      return $output;

    default:
  }
}
